import 'package:get/get.dart';

class TextData extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_IN': _english,
    'hi_IN': _hindi,
    'bn_IN': _bengali,
    'kn_IN': _kannada,
    'ur_IN': _urdu,
    'pa_IN': _punjabi,
    'gu_IN': _gujarati,
    'mr_IN': _marathi,
  };

  final Map<String, String> _english = {
    "appName": "MVVM GetX",
    "confirm": "Confirm",
    "doYouWantToExitTheApp": "Do you want to exit the App?",
    "yes": "Yes",
    "no": "No",
    "login": "Login",
    "register": "Register",
    "doNotHaveAnAccount": "Don't have an account?",
    "fullName": "Full Name",
    "mobileNumber": "Mobile Number",
    "verifyYourMobileNo": "Verify Your Mobile No.",
    "verifyOTP": "Verify OTP",
    "enterOTP": "Enter OTP here:",
    "submit": "Submit",
    "didNotGetOTP": "Didn't get OTP",
    "resendNow": "Resend Now",
    "confirmPassword": "Confirm Password",
    "alreadyHaveAnAccount": "Already have an account?",
    "logout": "Logout",
    "update": "Update",
    "noDataAvailable": "No Data Available",
    "thereIsNoDataToBeShown": "There is no data available to be shown here.",
    "myBusinessAndService": "My Business & Service",
    "search_": "Search...",
    "categories": "Categories",
    "viewMore": "View More",
    "location": "Location",
    "call": "Call",
    "message": "Message",
    "businesses": "Businesses",
    "services": "Services",
    "change": "Change",
    "searchCategory": "Search category",
    "searchService": "Search service",
    "searchBusiness": "Search business",
    "search": "Search",
    "noSearchResultTitle": "Sorry, no results found",
    "noSearchResultSubtitle":
        "What you searched is unfortunately not found or doesn't exist",
    "fromYourCurrentLocation": "from your current location",
    "rateIt": "Rate it",
    "howWasYourExperience": "How was your experience?",
    "add": "Add",
    "edit": "Edit",
    "delete": "Delete",
    "addBusinessService": "Add Business/Service",
    "selectImageSource": "Select Image Source",
    "gallery": "Gallery",
    "camera": "Camera",
    "fileSizeMustBeSmallerThan": "File size must be smaller than",
    "name": "Name",
    "address": "Address",
    "save": "Save",
    "type": "Type",
    "category": "Category",
    "country": "Country",
    "state": "State",
    "city": "City",
    "currentLocation": "Current Location",
    "selectLocation": "Select Location",
    "selectedLocation": "Selected Location",
    "productsAndOrServices": "Products and/or Services",
    "selectFromMap": "Select from Map",
    "pickLocation": "Pick Location",
    "or": "Or",
    "removeItem": "Remove Item",
    "cancel": "Cancel",
    "remove": "Remove",
    "doYouReallyWantToRemove": "Do you really want to remove '#'?",
    "openTime": "Open Time",
    "closeTime": "Close Time",
    "profile": "Profile",
    "appDoesNotHaveLocationPermission":
        "The App does not have the location permission. You will have to select the location manually to get proper results.",
    "important": "Important",
    "noInternet": "No Internet",
    "thereIsNoInternetConnectivity": "There is no internet connectivity.",
    "doYouWantToDeleteBusinessService":
        "Do you want to delete this Business/Service?",
    "active": "Active",
    "editBusinessService": "Edit Business/Service",
    "okay": "Okay",
    "loginRequired": "Login Required",
    "pleaseLoginToUseThisFeature": "Please login to use this feature.",
    "doYouWantToLogout": "Do you want to logout?",
    "history": "History",
    "clear": "Clear",
    "doYouWantToDeleteThisBusinessServiceFromHistory":
        "Do you want to delete this Business/Service from history?",
    "doYouWantToDeleteAllBusinessesServicesFromHistory":
        "Do you want to delete all Businesses/Services from history?",
    "noChats": "No Chats Now",
    "allChatsWillBeShownHere": "All chats will be shown here.",
    "doYouWantToDeleteThisMessage": "Do you want to delete this message?",
    "selectVideoSource": "Select Video Source",
    "video": "Video",
    "audio": "Audio",
    "pdf": "PDF",
    "image": "Image",
    "typing": "Typing...",
    "callHasBeenDisabledByTheBusinessService":
        "Call has been disabled by the business/service.",
    "messageHasBeenDisabledByTheBusinessService":
        "Message has been disabled by the business/service.",
    "loadingLocalBusinessAndServices":
        "Loading Local \nBusiness \nAnd \nServices",
    "sortByDistance": "Sort By Distance",
    "sortByRating": "Sort By Rating",
    "feedback": "Feedback",
    "writeYourFeedbackHere": "Write your feedback here...",
    "verifyYourBusinessService": "Verify Your Business & Service",
    "verificationForm": "Verification Form",
    "allSubmissions": "All Submissions",
    "documentFile": "Document File",
    "documentType": "Document Type",
    "documentNumber": "Document Number",
    "businessService": "Business/Service",
    "docFile": "Doc. File",
    "docType": "Doc. Type",
    "docNumber": "Doc. No.",
    "view": "View",
    "verified": "Verified",
    "status": "Status",
    "reason": "Reason",
    "date": "Date",
    "notification": "Notification",
    "notifications": "Notifications",
    "doYouWantToDeleteThisNotification":
        "Do you want to delete this notification?",
    "noNotifications": "No Notifications Now",
    "deleteAccount": "Delete Account",
    "whyDoYouWantToDeleteYourAccount":
        "Why do you want to delete your account?",
    "writeYourReasonHere": "Write your reason here...",
    "reasonIsRequired": "Reason is required.",
    "reasonMustBeAtLeast10Characters":
        "Reason must be at least \n10 characters long.",
    "selectLanguage": "Select Language",
    "english": "English",
    "hindi": "हिंदी",
    "bengali": "বাংলা",
    "kannada": "ಕನ್ನಡ",
    "urdu": "اردو",
    "punjabi": "ਪੰਜਾਬੀ",
    "gujarati": "ગુજરાતી",
    "marathi": "मराठी",
    "fullNameIsRequired": "Full Name is required.",
    "mobileNumberIsRequired": "Mobile number is required.",
    "enterAValid10DigitMobileNumber": "Enter a valid 10-digit mobile number.",
    "emailIsRequired": "Email is required.",
    "enterAValidEmailAddress": "Enter a valid email address.",
    "passwordIsRequired": "Password is required.",
    "passwordMustHaveAtLeast8Characters":
        "Password must have at least 8 characters.",
    "fieldIsRequired": "Field is required.",
    "thePasswordMustContainAtLeast":
        "The password must contain at least one uppercase \nletter, one lowercase letter and one number.",
    "passwordsDoNotMatch": "Passwords do not match.",
    "imageIsRequired": "Image is required.",
    "nameIsRequired": "Name is required.",
    "addressIsRequired": "Address is required.",
    "typeIsRequired": "Type is required.",
    "categoryIsRequired": "Category is required.",
    "countryIsRequired": "Country is required.",
    "stateIsRequired": "State is required.",
    "cityIsRequired": "City is required.",
    "pleaseAddAtLeastOneProductService":
        "Please add at least one product or service.",
    "openTimeIsRequired": "Open Time is required.",
    "closeTimeIsRequired": "Close Time is required.",
    "feedbackIsRequired": "Feedback is required.",
    "documentTypeIsRequired": "Document Type is required.",
    "businessServiceIsRequired": "Business/Service is required.",
    "documentNumberIsRequired": "Document Number is required.",
    "documentImageIsRequired": "Document Image is required.",
  };

  final Map<String, String> _hindi = {
    "appName": "MVVM GetX",
    "confirm": "पुष्टि करें",
    "doYouWantToExitTheApp": "क्या आप ऐप से बाहर निकलना चाहते हैं?",
    "yes": "हाँ",
    "no": "नहीं",
    "login": "लॉगिन",
    "register": "पंजीकरण करें",
    "doNotHaveAnAccount": "क्या आपका खाता नहीं है?",
    "fullName": "पूरा नाम",
    "mobileNumber": "मोबाइल नंबर",
    "verifyYourMobileNo": "अपने मोबाइल नंबर को सत्यापित करें",
    "verifyOTP": "ओटीपी सत्यापित करें",
    "enterOTP": "यहाँ ओटीपी दर्ज करें:",
    "submit": "जमा करें",
    "didNotGetOTP": "ओटीपी नहीं मिला",
    "resendNow": "फिर से भेजें",
    "confirmPassword": "पासवर्ड की पुष्टि करें",
    "alreadyHaveAnAccount": "क्या आपके पास पहले से खाता है?",
    "logout": "लॉगआउट",
    "update": "अपडेट करें",
    "noDataAvailable": "कोई डेटा उपलब्ध नहीं है",
    "thereIsNoDataToBeShown": "यहाँ दिखाने के लिए कोई डेटा उपलब्ध नहीं है।",
    "myBusinessAndService": "मेरा व्यवसाय और सेवा",
    "search_": "खोजें...",
    "categories": "श्रेणियाँ",
    "viewMore": "और देखें",
    "location": "स्थान",
    "call": "कॉल",
    "message": "संदेश",
    "businesses": "व्यवसाय",
    "services": "सेवाएँ",
    "change": "बदलें",
    "searchCategory": "श्रेणी खोजें",
    "searchService": "सेवा खोजें",
    "searchBusiness": "व्यवसाय खोजें",
    "search": "खोजें",
    "noSearchResultTitle": "माफ़ कीजिए, कोई परिणाम नहीं मिला",
    "noSearchResultSubtitle":
        "आपकी खोज का परिणाम नहीं मिला या वह मौजूद नहीं है",
    "fromYourCurrentLocation": "आपके वर्तमान स्थान से",
    "rateIt": "रेटिंग दें",
    "howWasYourExperience": "आपका अनुभव कैसा रहा?",
    "add": "जोड़ें",
    "edit": "संपादित करें",
    "delete": "हटाएँ",
    "addBusinessService": "व्यवसाय/सेवा जोड़ें",
    "selectImageSource": "छवि स्रोत चुनें",
    "gallery": "गैलरी",
    "camera": "कैमरा",
    "fileSizeMustBeSmallerThan": "फ़ाइल का आकार इससे छोटा होना चाहिए",
    "name": "नाम",
    "address": "पता",
    "save": "सहेजें",
    "type": "प्रकार",
    "category": "श्रेणी",
    "country": "देश",
    "state": "राज्य",
    "city": "शहर",
    "currentLocation": "वर्तमान स्थान",
    "selectLocation": "स्थान चुनें",
    "selectedLocation": "चयनित स्थान",
    "productsAndOrServices": "उत्पाद और/या सेवाएँ",
    "selectFromMap": "मानचित्र से चुनें",
    "pickLocation": "स्थान चुनें",
    "or": "या",
    "removeItem": "आइटम हटाएँ",
    "cancel": "रद्द करें",
    "remove": "हटाएँ",
    "doYouReallyWantToRemove": "क्या आप वास्तव में '#' को हटाना चाहते हैं?",
    "openTime": "खुलने का समय",
    "closeTime": "बंद होने का समय",
    "profile": "प्रोफ़ाइल",
    "appDoesNotHaveLocationPermission":
        "ऐप के पास स्थान की अनुमति नहीं है। कृपया मैन्युअली स्थान चुनें।",
    "important": "महत्वपूर्ण",
    "noInternet": "कोई इंटरनेट नहीं",
    "thereIsNoInternetConnectivity": "कोई इंटरनेट कनेक्टिविटी नहीं है।",
    "doYouWantToDeleteBusinessService":
        "क्या आप इस व्यवसाय/सेवा को हटाना चाहते हैं?",
    "active": "सक्रिय",
    "editBusinessService": "व्यवसाय/सेवा संपादित करें",
    "okay": "ठीक है",
    "loginRequired": "लॉगिन आवश्यक",
    "pleaseLoginToUseThisFeature":
        "कृपया इस सुविधा का उपयोग करने के लिए लॉगिन करें।",
    "doYouWantToLogout": "क्या आप लॉगआउट करना चाहते हैं?",
    "history": "इतिहास",
    "clear": "साफ करें",
    "doYouWantToDeleteThisBusinessServiceFromHistory":
        "क्या आप इतिहास से इस व्यवसाय/सेवा को हटाना चाहते हैं?",
    "doYouWantToDeleteAllBusinessesServicesFromHistory":
        "क्या आप इतिहास से सभी व्यवसाय/सेवाओं को हटाना चाहते हैं?",
    "noChats": "कोई चैट नहीं",
    "allChatsWillBeShownHere": "सभी चैट यहाँ दिखाई जाएँगी।",
    "doYouWantToDeleteThisMessage": "क्या आप इस संदेश को हटाना चाहते हैं?",
    "selectVideoSource": "वीडियो स्रोत चुनें",
    "video": "वीडियो",
    "audio": "ऑडियो",
    "pdf": "पीडीएफ",
    "image": "छवि",
    "typing": "टाइप कर रहे हैं...",
    "callHasBeenDisabledByTheBusinessService":
        "व्यवसाय/सेवा द्वारा कॉल अक्षम कर दी गई है।",
    "messageHasBeenDisabledByTheBusinessService":
        "व्यवसाय/सेवा द्वारा संदेश अक्षम कर दिया गया है।",
    "loadingLocalBusinessAndServices":
        "स्थानीय व्यवसाय \nऔर \nसेवाएँ \nलोड हो रही हैं",
    "sortByDistance": "दूरी के अनुसार क्रमबद्ध करें",
    "sortByRating": "रेटिंग के अनुसार क्रमबद्ध करें",
    "feedback": "प्रतिक्रिया",
    "writeYourFeedbackHere": "अपनी प्रतिक्रिया यहाँ लिखें...",
    "verifyYourBusinessService": "अपने व्यवसाय और सेवा को सत्यापित करें",
    "verificationForm": "सत्यापन फॉर्म",
    "allSubmissions": "सभी प्रस्तुतियाँ",
    "documentFile": "दस्तावेज़ फ़ाइल",
    "documentType": "दस्तावेज़ प्रकार",
    "documentNumber": "दस्तावेज़ संख्या",
    "businessService": "व्यवसाय/सेवा",
    "docFile": "दस्तावेज़ फ़ाइल",
    "docType": "दस्तावेज़ प्रकार",
    "docNumber": "दस्तावेज़ सं.",
    "view": "देखें",
    "verified": "सत्यापित",
    "status": "स्थिति",
    "reason": "कारण",
    "date": "तारीख",
    "notification": "सूचना",
    "notifications": "सूचनाएँ",
    "doYouWantToDeleteThisNotification": "क्या आप इस सूचना को हटाना चाहते हैं?",
    "noNotifications": "कोई सूचनाएँ नहीं",
    "deleteAccount": "खाता हटाएं",
    "whyDoYouWantToDeleteYourAccount": "आप अपना खाता क्यों हटाना चाहते हैं?",
    "writeYourReasonHere": "अपना कारण यहाँ लिखें...",
    "reasonIsRequired": "कारण आवश्यक है।",
    "reasonMustBeAtLeast10Characters":
        "कारण कम से कम\n10 अक्षरों का होना चाहिए।",
    "selectLanguage": "भाषा चुनें",
    "english": "English",
    "hindi": "हिंदी",
    "bengali": "বাংলা",
    "kannada": "ಕನ್ನಡ",
    "urdu": "اردو",
    "punjabi": "ਪੰਜਾਬੀ",
    "gujarati": "ગુજરાતી",
    "marathi": "मराठी",
    "fullNameIsRequired": "पूरा नाम आवश्यक है।",
    "mobileNumberIsRequired": "मोबाइल नंबर आवश्यक है।",
    "enterAValid10DigitMobileNumber":
        "कृपया वैध 10 अंकों का मोबाइल नंबर दर्ज करें।",
    "emailIsRequired": "ईमेल आवश्यक है।",
    "enterAValidEmailAddress": "कृपया एक वैध ईमेल पता दर्ज करें।",
    "passwordIsRequired": "पासवर्ड आवश्यक है।",
    "passwordMustHaveAtLeast8Characters":
        "पासवर्ड में कम से कम 8 अक्षर होने चाहिए।",
    "fieldIsRequired": "यह फ़ील्ड आवश्यक है।",
    "thePasswordMustContainAtLeast":
        "पासवर्ड में कम से कम एक बड़े अक्षर, एक छोटे अक्षर और एक संख्या होनी चाहिए।",
    "passwordsDoNotMatch": "पासवर्ड मेल नहीं खाते।",
    "imageIsRequired": "छवि आवश्यक है।",
    "nameIsRequired": "नाम आवश्यक है।",
    "addressIsRequired": "पता आवश्यक है।",
    "typeIsRequired": "प्रकार आवश्यक है।",
    "categoryIsRequired": "श्रेणी आवश्यक है।",
    "countryIsRequired": "देश आवश्यक है।",
    "stateIsRequired": "राज्य आवश्यक है।",
    "cityIsRequired": "शहर आवश्यक है।",
    "pleaseAddAtLeastOneProductService":
        "कृपया कम से कम एक उत्पाद या सेवा जोड़ें।",
    "openTimeIsRequired": "खुलने का समय आवश्यक है।",
    "closeTimeIsRequired": "बंद होने का समय आवश्यक है।",
    "feedbackIsRequired": "प्रतिक्रिया आवश्यक है।",
    "documentTypeIsRequired": "दस्तावेज़ प्रकार आवश्यक है।",
    "businessServiceIsRequired": "व्यवसाय/सेवा आवश्यक है।",
    "documentNumberIsRequired": "दस्तावेज़ संख्या आवश्यक है।",
    "documentImageIsRequired": "दस्तावेज़ छवि आवश्यक है।",
  };

  final Map<String, String> _bengali = {
    "appName": "MVVM GetX",
    "confirm": "নিশ্চিত করুন",
    "doYouWantToExitTheApp": "আপনি কি অ্যাপ থেকে বের হতে চান?",
    "yes": "হ্যাঁ",
    "no": "না",
    "login": "লগইন",
    "register": "রেজিস্টার",
    "doNotHaveAnAccount": "আপনার কোনো অ্যাকাউন্ট নেই?",
    "fullName": "পূর্ণ নাম",
    "mobileNumber": "মোবাইল নম্বর",
    "verifyYourMobileNo": "আপনার মোবাইল নম্বর যাচাই করুন",
    "verifyOTP": "OTP যাচাই করুন",
    "enterOTP": "এখানে OTP লিখুন:",
    "submit": "জমা দিন",
    "didNotGetOTP": "OTP পাননি?",
    "resendNow": "আবার পাঠান",
    "confirmPassword": "পাসওয়ার্ড নিশ্চিত করুন",
    "alreadyHaveAnAccount": "ইতিমধ্যে একটি অ্যাকাউন্ট আছে?",
    "logout": "লগআউট",
    "update": "আপডেট",
    "noDataAvailable": "কোনো তথ্য নেই",
    "thereIsNoDataToBeShown": "এখানে প্রদর্শনের জন্য কোনো তথ্য নেই।",
    "myBusinessAndService": "আমার ব্যবসা ও পরিষেবা",
    "search_": "অনুসন্ধান করুন...",
    "categories": "বিভাগ",
    "viewMore": "আরো দেখুন",
    "location": "অবস্থান",
    "call": "কল",
    "message": "বার্তা",
    "businesses": "ব্যবসা",
    "services": "পরিষেবা",
    "change": "পরিবর্তন",
    "searchCategory": "বিভাগ অনুসন্ধান",
    "searchService": "পরিষেবা অনুসন্ধান",
    "searchBusiness": "ব্যবসা অনুসন্ধান",
    "search": "অনুসন্ধান",
    "noSearchResultTitle": "দুঃখিত, কোনো ফলাফল পাওয়া যায়নি",
    "noSearchResultSubtitle":
        "আপনি যা অনুসন্ধান করেছেন তা পাওয়া যায়নি বা বিদ্যমান নেই",
    "fromYourCurrentLocation": "আপনার বর্তমান অবস্থান থেকে",
    "rateIt": "রেট দিন",
    "howWasYourExperience": "আপনার অভিজ্ঞতা কেমন ছিল?",
    "add": "যোগ করুন",
    "edit": "সম্পাদনা",
    "delete": "মুছে ফেলুন",
    "addBusinessService": "ব্যবসা/পরিষেবা যোগ করুন",
    "selectImageSource": "ছবির উৎস নির্বাচন করুন",
    "gallery": "গ্যালারি",
    "camera": "ক্যামেরা",
    "fileSizeMustBeSmallerThan": "ফাইলের আকার এর চেয়ে ছোট হতে হবে",
    "name": "নাম",
    "address": "ঠিকানা",
    "save": "সংরক্ষণ করুন",
    "type": "ধরন",
    "category": "বিভাগ",
    "country": "দেশ",
    "state": "রাজ্য",
    "city": "শহর",
    "currentLocation": "বর্তমান অবস্থান",
    "selectLocation": "অবস্থান নির্বাচন করুন",
    "selectedLocation": "নির্বাচিত অবস্থান",
    "productsAndOrServices": "পণ্য এবং/অথবা পরিষেবা",
    "selectFromMap": "মানচিত্র থেকে নির্বাচন করুন",
    "pickLocation": "অবস্থান নির্বাচন করুন",
    "or": "অথবা",
    "removeItem": "আইটেম সরান",
    "cancel": "বাতিল",
    "remove": "সরান",
    "doYouReallyWantToRemove": "আপনি কি সত্যিই '#' সরাতে চান?",
    "openTime": "খোলার সময়",
    "closeTime": "বন্ধের সময়",
    "profile": "প্রোফাইল",
    "appDoesNotHaveLocationPermission":
        "অ্যাপের অবস্থান অনুমতি নেই। সঠিক ফলাফলের জন্য আপনাকে অবস্থান ম্যানুয়ালি নির্বাচন করতে হবে।",
    "important": "গুরুত্বপূর্ণ",
    "noInternet": "ইন্টারনেট নেই",
    "thereIsNoInternetConnectivity": "কোনো ইন্টারনেট সংযোগ নেই।",
    "doYouWantToDeleteBusinessService":
        "আপনি কি এই ব্যবসা/পরিষেবাটি মুছে ফেলতে চান?",
    "active": "সক্রিয়",
    "editBusinessService": "ব্যবসা/পরিষেবা সম্পাদনা করুন",
    "okay": "ঠিক আছে",
    "loginRequired": "লগইন প্রয়োজন",
    "pleaseLoginToUseThisFeature": "এই বৈশিষ্ট্যটি ব্যবহার করতে লগইন করুন।",
    "doYouWantToLogout": "আপনি কি লগআউট করতে চান?",
    "history": "ইতিহাস",
    "clear": "পরিষ্কার করুন",
    "doYouWantToDeleteThisBusinessServiceFromHistory":
        "আপনি কি এই ব্যবসা/পরিষেবাটি ইতিহাস থেকে মুছে ফেলতে চান?",
    "doYouWantToDeleteAllBusinessesServicesFromHistory":
        "আপনি কি সমস্ত ব্যবসা/পরিষেবাগুলি ইতিহাস থেকে মুছে ফেলতে চান?",
    "noChats": "এখনো কোনো চ্যাট নেই",
    "allChatsWillBeShownHere": "সব চ্যাট এখানে দেখানো হবে।",
    "doYouWantToDeleteThisMessage": "আপনি কি এই বার্তাটি মুছে ফেলতে চান?",
    "selectVideoSource": "ভিডিও উৎস নির্বাচন করুন",
    "video": "ভিডিও",
    "audio": "অডিও",
    "pdf": "PDF",
    "image": "ছবি",
    "typing": "টাইপ করছে...",
    "callHasBeenDisabledByTheBusinessService":
        "এই ব্যবসা/পরিষেবার দ্বারা কল নিষ্ক্রিয় করা হয়েছে।",
    "messageHasBeenDisabledByTheBusinessService":
        "এই ব্যবসা/পরিষেবার দ্বারা বার্তা নিষ্ক্রিয় করা হয়েছে।",
    "loadingLocalBusinessAndServices":
        "স্থানীয় \nব্যবসা ও \nপরিষেবা \nলোড হচ্ছে",
    "sortByDistance": "দূরত্ব অনুসারে সাজান",
    "sortByRating": "রেটিং অনুসারে সাজান",
    "feedback": "মতামত",
    "writeYourFeedbackHere": "এখানে আপনার মতামত লিখুন...",
    "verifyYourBusinessService": "আপনার ব্যবসা ও পরিষেবা যাচাই করুন",
    "verificationForm": "যাচাইকরণ ফর্ম",
    "allSubmissions": "সমস্ত জমা",
    "documentFile": "নথির ফাইল",
    "documentType": "নথির ধরন",
    "documentNumber": "নথি নম্বর",
    "businessService": "ব্যবসা/পরিষেবা",
    "docFile": "ডক. ফাইল",
    "docType": "ডক. ধরন",
    "docNumber": "ডক. নম্বর",
    "view": "দেখুন",
    "verified": "যাচাই করা হয়েছে",
    "status": "স্থিতি",
    "reason": "কারণ",
    "date": "তারিখ",
    "notification": "বিজ্ঞপ্তি",
    "notifications": "বিজ্ঞপ্তিসমূহ",
    "doYouWantToDeleteThisNotification":
        "আপনি কি এই বিজ্ঞপ্তিটি মুছে ফেলতে চান?",
    "noNotifications": "এখনো কোনো বিজ্ঞপ্তি নেই",
    "deleteAccount": "অ্যাকাউন্ট মুছে ফেলুন",
    "whyDoYouWantToDeleteYourAccount":
        "আপনি আপনার অ্যাকাউন্ট মুছে ফেলতে চান কেন?",
    "writeYourReasonHere": "আপনার কারণ এখানে লিখুন...",
    "reasonIsRequired": "কারণ প্রয়োজন।",
    "reasonMustBeAtLeast10Characters": "কারণ কমপক্ষে\n১০ অক্ষরের হতে হবে।",
    "selectLanguage": "ভাষা নির্বাচন করুন",
    "english": "English",
    "hindi": "हिंदी",
    "bengali": "বাংলা",
    "kannada": "ಕನ್ನಡ",
    "urdu": "اردو",
    "punjabi": "ਪੰਜਾਬੀ",
    "gujarati": "ગુજરાતી",
    "marathi": "मराठी",
    "fullNameIsRequired": "পূর্ণ নাম আবশ্যক।",
    "mobileNumberIsRequired": "মোবাইল নম্বর আবশ্যক।",
    "enterAValid10DigitMobileNumber": "একটি বৈধ ১০-সংখ্যার মোবাইল নম্বর লিখুন।",
    "emailIsRequired": "ইমেইল আবশ্যক।",
    "enterAValidEmailAddress": "একটি বৈধ ইমেইল ঠিকানা লিখুন।",
    "passwordIsRequired": "পাসওয়ার্ড আবশ্যক।",
    "passwordMustHaveAtLeast8Characters":
        "পাসওয়ার্ডে অন্তত ৮টি অক্ষর থাকতে হবে।",
    "fieldIsRequired": "ঘরটি পূরণ আবশ্যক।",
    "thePasswordMustContainAtLeast":
        "পাসওয়ার্ডে অন্তত একটি বড় হাতের অক্ষর, একটি ছোট হাতের অক্ষর এবং একটি সংখ্যা থাকতে হবে।",
    "passwordsDoNotMatch": "পাসওয়ার্ড মিলছে না।",
    "imageIsRequired": "ছবি আবশ্যক।",
    "nameIsRequired": "নাম আবশ্যক।",
    "addressIsRequired": "ঠিকানা আবশ্যক।",
    "typeIsRequired": "ধরন আবশ্যক।",
    "categoryIsRequired": "বিভাগ আবশ্যক।",
    "countryIsRequired": "দেশ আবশ্যক।",
    "stateIsRequired": "রাজ্য আবশ্যক।",
    "cityIsRequired": "শহর আবশ্যক।",
    "pleaseAddAtLeastOneProductService":
        "কমপক্ষে একটি পণ্য বা পরিষেবা যোগ করুন।",
    "openTimeIsRequired": "খোলার সময় আবশ্যক।",
    "closeTimeIsRequired": "বন্ধের সময় আবশ্যক।",
    "feedbackIsRequired": "মতামত আবশ্যক।",
    "documentTypeIsRequired": "নথির ধরন আবশ্যক।",
    "businessServiceIsRequired": "ব্যবসা/পরিষেবা আবশ্যক।",
    "documentNumberIsRequired": "নথি নম্বর আবশ্যক।",
    "documentImageIsRequired": "নথির ছবি আবশ্যক।",
  };

  final Map<String, String> _kannada = {
    "appName": "MVVM GetX",
    "confirm": "ದೃಢೀಕರಿಸಿ",
    "doYouWantToExitTheApp": "ನೀವು ಅಪ್ಲಿಕೇಶನ್ ಅನ್ನು ತ್ಯಜಿಸಲು ಇಚ್ಛಿಸುತ್ತೀರಾ?",
    "yes": "ಹೌದು",
    "no": "ಇಲ್ಲ",
    "login": "ಲಾಗಿನ್",
    "register": "ನೋಂದಣಿ",
    "doNotHaveAnAccount": "ಖಾತೆ ಇಲ್ಲವೆ?",
    "fullName": "ಪೂರ್ಣ ಹೆಸರು",
    "mobileNumber": "ಮೊಬೈಲ್ ನಂಬರ್",
    "verifyYourMobileNo": "ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ಪರಿಶೀಲಿಸಿ",
    "verifyOTP": "OTP ಪರಿಶೀಲಿಸಿ",
    "enterOTP": "OTP ನಮೂದಿಸಿ:",
    "submit": "ಸಲ್ಲಿಸು",
    "didNotGetOTP": "OTP ಸಿಕ್ಕಿಲ್ಲವೆ?",
    "resendNow": "ಈಗ ಮತ್ತೆ ಕಳುಹಿಸಿ",
    "confirmPassword": "ಪಾಸ್ವರ್ಡ್ ದೃಢೀಕರಿಸಿ",
    "alreadyHaveAnAccount": "ಈಗಾಗಲೇ ಖಾತೆ ಇದೆ?",
    "logout": "ಲಾಗ್ ಔಟ್",
    "update": "ನವೀಕರಿಸಿ",
    "noDataAvailable": "ಡೇಟಾ ಲಭ್ಯವಿಲ್ಲ",
    "thereIsNoDataToBeShown": "ಇಲ್ಲಿ ತೋರಿಸಲು ಯಾವುದೇ ಡೇಟಾ ಲಭ್ಯವಿಲ್ಲ.",
    "myBusinessAndService": "ನನ್ನ ವ್ಯವಹಾರ ಮತ್ತು ಸೇವೆ",
    "search_": "ಹುಡುಕಿ...",
    "categories": "ವರ್ಗಗಳು",
    "viewMore": "ಇನ್ನಷ್ಟು ವೀಕ್ಷಿಸಿ",
    "location": "ಸ್ಥಳ",
    "call": "ಕರೆ",
    "message": "ಸಂದೇಶ",
    "businesses": "ವ್ಯವಹಾರಗಳು",
    "services": "ಸೇವೆಗಳು",
    "change": "ಬದಲಾಯಿಸಿ",
    "searchCategory": "ವರ್ಗ ಹುಡುಕಿ",
    "searchService": "ಸೇವೆ ಹುಡುಕಿ",
    "searchBusiness": "ವ್ಯವಹಾರ ಹುಡುಕಿ",
    "search": "ಹುಡುಕಿ",
    "noSearchResultTitle": "ಕ್ಷಮಿಸಿ, ಫಲಿತಾಂಶ ಕಂಡುಬಂದಿಲ್ಲ",
    "noSearchResultSubtitle": "ನೀವು ಹುಡುಕಿದುದು ಲಭ್ಯವಿಲ್ಲ ಅಥವಾ ಅಸ್ತಿತ್ವದಲ್ಲಿಲ್ಲ",
    "fromYourCurrentLocation": "ನಿಮ್ಮ ಪ್ರಸ್ತುತ ಸ್ಥಳದಿಂದ",
    "rateIt": "ಮೌಲ್ಯಮಾಪನ ಮಾಡಿ",
    "howWasYourExperience": "ನಿಮ್ಮ ಅನುಭವ ಹೇಗಿತ್ತು?",
    "add": "ಸೇರಿಸಿ",
    "edit": "ಸಂಪಾದಿಸಿ",
    "delete": "ಅಳಿಸಿ",
    "addBusinessService": "ವ್ಯವಹಾರ/ಸೇವೆ ಸೇರಿಸಿ",
    "selectImageSource": "ಚಿತ್ರ ಮೂಲ ಆಯ್ಕೆಮಾಡಿ",
    "gallery": "ಗ್ಯಾಲರಿ",
    "camera": "ಕ್ಯಾಮೆರಾ",
    "fileSizeMustBeSmallerThan": "ಫೈಲ್ ಗಾತ್ರವು ಇದಕ್ಕಿಂತ ಕಡಿಮೆಯಾಗಿರಬೇಕು",
    "name": "ಹೆಸರು",
    "address": "ವಿಳಾಸ",
    "save": "ಉಳಿಸಿ",
    "type": "ಪ್ರಕಾರ",
    "category": "ವರ್ಗ",
    "country": "ದೇಶ",
    "state": "ರಾಜ್ಯ",
    "city": "ನಗರ",
    "currentLocation": "ಪ್ರಸ್ತುತ ಸ್ಥಳ",
    "selectLocation": "ಸ್ಥಳ ಆಯ್ಕೆಮಾಡಿ",
    "selectedLocation": "ಆಯ್ದ ಸ್ಥಳ",
    "productsAndOrServices": "ಉತ್ಪನ್ನಗಳು ಮತ್ತು/ಅಥವಾ ಸೇವೆಗಳು",
    "selectFromMap": "ನಕ್ಷೆ ಯಿಂದ ಆಯ್ಕೆಮಾಡಿ",
    "pickLocation": "ಸ್ಥಳ ಆಯ್ಕೆಮಾಡಿ",
    "or": "ಅಥವಾ",
    "removeItem": "ಐಟಂ ತೆಗೆದುಹಾಕಿ",
    "cancel": "ರದ್ದುಮಾಡಿ",
    "remove": "ತೆಗೆದುಹಾಕಿ",
    "doYouReallyWantToRemove": "'#' ಅನ್ನು ನಿಜವಾಗಿಯೂ ತೆಗೆದುಹಾಕಬೇಕೆ?",
    "openTime": "ತೆರೆಯುವ ಸಮಯ",
    "closeTime": "ಮುಚ್ಚುವ ಸಮಯ",
    "profile": "ಪ್ರೊಫೈಲ್",
    "appDoesNotHaveLocationPermission":
        "ಅಪ್ಲಿಕೇಶನ್ ಗೆ ಸ್ಥಳ ಅನುಮತಿ ಇಲ್ಲ. ಸರಿಯಾದ ಫಲಿತಾಂಶಕ್ಕಾಗಿ ನೀವು ಸ್ಥಳವನ್ನು ಕೈಯಿಂದ ಆಯ್ಕೆಮಾಡಬೇಕು.",
    "important": "ಮುಖ್ಯ",
    "noInternet": "ಇಂಟರ್‌ನೆಟ್ ಇಲ್ಲ",
    "thereIsNoInternetConnectivity": "ಇಂಟರ್‌ನೆಟ್ ಸಂಪರ್ಕ ಲಭ್ಯವಿಲ್ಲ.",
    "doYouWantToDeleteBusinessService":
        "ಈ ವ್ಯವಹಾರ/ಸೇವೆಯನ್ನು ಅಳಿಸಲು ಇಚ್ಛಿಸುತ್ತೀರಾ?",
    "active": "ಸಕ್ರಿಯ",
    "editBusinessService": "ವ್ಯವಹಾರ/ಸೇವೆ ಸಂಪಾದಿಸಿ",
    "okay": "ಸರಿ",
    "loginRequired": "ಲಾಗಿನ್ ಅಗತ್ಯವಿದೆ",
    "pleaseLoginToUseThisFeature":
        "ಈ ವೈಶಿಷ್ಟ್ಯವನ್ನು ಬಳಸಲು ದಯವಿಟ್ಟು ಲಾಗಿನ್ ಮಾಡಿ.",
    "doYouWantToLogout": "ಲಾಗ್ ಔಟ್ ಆಗಲು ಇಚ್ಛಿಸುತ್ತೀರಾ?",
    "history": "ಅಿತಿಹಾಸ",
    "clear": "ತೆರೆ",
    "doYouWantToDeleteThisBusinessServiceFromHistory":
        "ಇತಿಹಾಸದಿಂದ ಈ ವ್ಯವಹಾರ/ಸೇವೆಯನ್ನು ಅಳಿಸಲು ಇಚ್ಛಿಸುತ್ತೀರಾ?",
    "doYouWantToDeleteAllBusinessesServicesFromHistory":
        "ಇತಿಹಾಸದಿಂದ ಎಲ್ಲಾ ವ್ಯವಹಾರಗಳು/ಸೇವೆಗಳನ್ನು ಅಳಿಸಲು ಇಚ್ಛಿಸುತ್ತೀರಾ?",
    "noChats": "ಈಗ ಚಾಟ್‌ಗಳಿಲ್ಲ",
    "allChatsWillBeShownHere": "ಎಲ್ಲಾ ಚಾಟ್‌ಗಳು ಇಲ್ಲಿ ತೋರಿಸಲಾಗುತ್ತವೆ.",
    "doYouWantToDeleteThisMessage": "ಈ ಸಂದೇಶವನ್ನು ಅಳಿಸಲು ಇಚ್ಛಿಸುತ್ತೀರಾ?",
    "selectVideoSource": "ವೀಡಿಯೋ ಮೂಲ ಆಯ್ಕೆಮಾಡಿ",
    "video": "ವೀಡಿಯೋ",
    "audio": "ಆಡಿಯೋ",
    "pdf": "ಪಿಡಿಎಫ್",
    "image": "ಚಿತ್ರ",
    "typing": "ಟೈಪಿಂಗ್...",
    "callHasBeenDisabledByTheBusinessService":
        "ವ್ಯವಹಾರ/ಸೇವೆಯಿಂದ ಕರೆ ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ.",
    "messageHasBeenDisabledByTheBusinessService":
        "ವ್ಯವಹಾರ/ಸೇವೆಯಿಂದ ಸಂದೇಶ ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ.",
    "loadingLocalBusinessAndServices":
        "ಸ್ಥಳೀಯ ವ್ಯವಹಾರಗಳು ಮತ್ತು ಸೇವೆಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ",
    "sortByDistance": "ಅಂತರದ ಆಧಾರದ ಮೇಲೆ ಕ್ರಮಗೊಳಿಸಿ",
    "sortByRating": "ರೇಟಿಂಗ್ ಆಧಾರದ ಮೇಲೆ ಕ್ರಮಗೊಳಿಸಿ",
    "feedback": "ಪ್ರತಿಕ್ರಿಯೆ",
    "writeYourFeedbackHere": "ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ಇಲ್ಲಿ ಬರೆಯಿರಿ...",
    "verifyYourBusinessService": "ನಿಮ್ಮ ವ್ಯವಹಾರ/ಸೇವೆಯನ್ನು ಪರಿಶೀಲಿಸಿ",
    "verificationForm": "ಪರಿಶೀಲನಾ ಫಾರ್ಮ್",
    "allSubmissions": "ಎಲ್ಲಾ ಸಲ್ಲಿಕೆಗಳು",
    "documentFile": "ಡಾಕ್ಯುಮೆಂಟ್ ಫೈಲ್",
    "documentType": "ಡಾಕ್ಯುಮೆಂಟ್ ಪ್ರಕಾರ",
    "documentNumber": "ಡಾಕ್ಯುಮೆಂಟ್ ಸಂಖ್ಯೆ",
    "businessService": "ವ್ಯವಹಾರ/ಸೇವೆ",
    "docFile": "ಡಾಕ್. ಫೈಲ್",
    "docType": "ಡಾಕ್. ಪ್ರಕಾರ",
    "docNumber": "ಡಾಕ್. ನಂ.",
    "view": "ವೀಕ್ಷಿಸಿ",
    "verified": "ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
    "status": "ಸ್ಥಿತಿ",
    "reason": "ಕಾರಣ",
    "date": "ದಿನಾಂಕ",
    "notification": "ಅಧಿಸೂಚನೆ",
    "notifications": "ಅಧಿಸೂಚನೆಗಳು",
    "doYouWantToDeleteThisNotification":
        "ಈ ಅಧಿಸೂಚನೆಯನ್ನು ಅಳಿಸಲು ಇಚ್ಛಿಸುತ್ತೀರಾ?",
    "noNotifications": "ಈಗ ಅಧಿಸೂಚನೆಗಳಿಲ್ಲ",
    "deleteAccount": "ಖಾತೆ ಅಳಿಸಿ",
    "whyDoYouWantToDeleteYourAccount":
        "ನೀವು ನಿಮ್ಮ ಖಾತೆಯನ್ನು ಏಕೆ ಅಳಿಸಲು ಇಚ್ಛಿಸುತ್ತೀರಿ?",
    "writeYourReasonHere": "ನಿಮ್ಮ ಕಾರಣವನ್ನು ಇಲ್ಲಿ ಬರೆಹಿಸಿ...",
    "reasonIsRequired": "ಕಾರಣ ಅಗತ್ಯವಿದೆ.",
    "reasonMustBeAtLeast10Characters": "ಕಾರಣ ಕನಿಷ್ಠ\n10 ಅಕ್ಷರಗಳಂತಿರಬೇಕು.",
    "selectLanguage": "ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ",
    "english": "English",
    "hindi": "हिंदी",
    "bengali": "বাংলা",
    "kannada": "ಕನ್ನಡ",
    "urdu": "اردو",
    "punjabi": "ਪੰਜਾਬੀ",
    "gujarati": "ગુજરાતી",
    "marathi": "मराठी",
    "fullNameIsRequired": "ಪೂರ್ಣ ಹೆಸರು ಅಗತ್ಯವಿದೆ.",
    "mobileNumberIsRequired": "ಮೊಬೈಲ್ ನಂಬರ್ ಅಗತ್ಯವಿದೆ.",
    "enterAValid10DigitMobileNumber":
        "ಮಾನ್ಯವಾದ 10 ಅಂಕೆಯ ಮೊಬೈಲ್ ನಂಬರ್ ನಮೂದಿಸಿ.",
    "emailIsRequired": "ಇಮೇಲ್ ಅಗತ್ಯವಿದೆ.",
    "enterAValidEmailAddress": "ಮಾನ್ಯವಾದ ಇಮೇಲ್ ವಿಳಾಸವನ್ನು ನಮೂದಿಸಿ.",
    "passwordIsRequired": "ಪಾಸ್ವರ್ಡ್ ಅಗತ್ಯವಿದೆ.",
    "passwordMustHaveAtLeast8Characters":
        "ಪಾಸ್ವರ್ಡ್ ಕನಿಷ್ಠ 8 ಅಕ್ಷರಗಳಿರುವುದಿರಬೇಕು.",
    "fieldIsRequired": "ಈ ಕ್ಷೇತ್ರ ಅಗತ್ಯವಿದೆ.",
    "thePasswordMustContainAtLeast":
        "ಪಾಸ್ವರ್ಡ್ ಕನಿಷ್ಠ ಒಂದು ದೊಡ್ಡ ಅಕ್ಷರ, ಒಂದು ಸಣ್ಣ ಅಕ್ಷರ ಮತ್ತು ಒಂದು ಸಂಖ್ಯೆ ಇರಬೇಕಾಗಿರುತ್ತದೆ.",
    "passwordsDoNotMatch": "ಪಾಸ್ವರ್ಡ್‌ಗಳು ಹೋಲುತ್ತಿಲ್ಲ.",
    "imageIsRequired": "ಚಿತ್ರ ಅಗತ್ಯವಿದೆ.",
    "nameIsRequired": "ಹೆಸರು ಅಗತ್ಯವಿದೆ.",
    "addressIsRequired": "ವಿಳಾಸ ಅಗತ್ಯವಿದೆ.",
    "typeIsRequired": "ಪ್ರಕಾರ ಅಗತ್ಯವಿದೆ.",
    "categoryIsRequired": "ವರ್ಗ ಅಗತ್ಯವಿದೆ.",
    "countryIsRequired": "ದೇಶ ಅಗತ್ಯವಿದೆ.",
    "stateIsRequired": "ರಾಜ್ಯ ಅಗತ್ಯವಿದೆ.",
    "cityIsRequired": "ನಗರ ಅಗತ್ಯವಿದೆ.",
    "pleaseAddAtLeastOneProductService":
        "ದಯವಿಟ್ಟು ಕನಿಷ್ಠ ಒಂದು ಉತ್ಪನ್ನ ಅಥವಾ ಸೇವೆ ಸೇರಿಸಿ.",
    "openTimeIsRequired": "ತೆರೆಯುವ ಸಮಯ ಅಗತ್ಯವಿದೆ.",
    "closeTimeIsRequired": "ಮುಚ್ಚುವ ಸಮಯ ಅಗತ್ಯವಿದೆ.",
    "feedbackIsRequired": "ಪ್ರತಿಕ್ರಿಯೆ ಅಗತ್ಯವಿದೆ.",
    "documentTypeIsRequired": "ಡಾಕ್ಯುಮೆಂಟ್ ಪ್ರಕಾರ ಅಗತ್ಯವಿದೆ.",
    "businessServiceIsRequired": "ವ್ಯವಹಾರ/ಸೇವೆ ಅಗತ್ಯವಿದೆ.",
    "documentNumberIsRequired": "ಡಾಕ್ಯುಮೆಂಟ್ ಸಂಖ್ಯೆ ಅಗತ್ಯವಿದೆ.",
    "documentImageIsRequired": "ಡಾಕ್ಯುಮೆಂಟ್ ಚಿತ್ರ ಅಗತ್ಯವಿದೆ.",
  };

  final Map<String, String> _urdu = {
    "appName": "MVVM GetX",
    "confirm": "تصدیق کریں",
    "doYouWantToExitTheApp": "کیا آپ ایپ سے باہر نکلنا چاہتے ہیں؟",
    "yes": "ہاں",
    "no": "نہیں",
    "login": "لاگ ان",
    "register": "رجسٹر کریں",
    "doNotHaveAnAccount": "کیا آپ کا اکاؤنٹ نہیں ہے؟",
    "fullName": "پورا نام",
    "mobileNumber": "موبائل نمبر",
    "verifyYourMobileNo": "اپنا موبائل نمبر تصدیق کریں",
    "verifyOTP": "OTP کی تصدیق کریں",
    "enterOTP": "یہاں OTP درج کریں:",
    "submit": "جمع کروائیں",
    "didNotGetOTP": "OTP نہیں ملا",
    "resendNow": "ابھی دوبارہ بھیجیں",
    "confirmPassword": "پاس ورڈ کی تصدیق کریں",
    "alreadyHaveAnAccount": "کیا آپ کا پہلے سے اکاؤنٹ ہے؟",
    "logout": "لاگ آؤٹ",
    "update": "اپ ڈیٹ کریں",
    "noDataAvailable": "کوئی ڈیٹا دستیاب نہیں ہے",
    "thereIsNoDataToBeShown": "یہاں دکھانے کے لیے کوئی ڈیٹا دستیاب نہیں ہے۔",
    "myBusinessAndService": "میرا کاروبار اور سروس",
    "search_": "تلاش کریں...",
    "categories": "اقسام",
    "viewMore": "مزید دیکھیں",
    "location": "مقام",
    "call": "کال کریں",
    "message": "پیغام",
    "businesses": "کاروبار",
    "services": "سروسز",
    "change": "تبدیل کریں",
    "searchCategory": "زمرہ تلاش کریں",
    "searchService": "سروس تلاش کریں",
    "searchBusiness": "کاروبار تلاش کریں",
    "search": "تلاش کریں",
    "noSearchResultTitle": "معذرت، کوئی نتائج نہیں ملے",
    "noSearchResultSubtitle":
        "جو آپ نے تلاش کیا وہ بدقسمتی سے نہیں ملا یا موجود نہیں ہے",
    "fromYourCurrentLocation": "آپ کے موجودہ مقام سے",
    "rateIt": "درجہ بندی کریں",
    "howWasYourExperience": "آپ کا تجربہ کیسا رہا؟",
    "add": "شامل کریں",
    "edit": "ترمیم کریں",
    "delete": "حذف کریں",
    "addBusinessService": "کاروبار/سروس شامل کریں",
    "selectImageSource": "تصویر کا ماخذ منتخب کریں",
    "gallery": "گیلری",
    "camera": "کیمرہ",
    "fileSizeMustBeSmallerThan": "فائل کا سائز اس سے کم ہونا چاہیے",
    "name": "نام",
    "address": "پتہ",
    "save": "محفوظ کریں",
    "type": "قسم",
    "category": "زمرہ",
    "country": "ملک",
    "state": "ریاست",
    "city": "شہر",
    "currentLocation": "موجودہ مقام",
    "selectLocation": "مقام منتخب کریں",
    "selectedLocation": "منتخب شدہ مقام",
    "productsAndOrServices": "مصنوعات اور/یا سروسز",
    "selectFromMap": "نقشے سے منتخب کریں",
    "pickLocation": "مقام منتخب کریں",
    "or": "یا",
    "removeItem": "آئٹم ہٹائیں",
    "cancel": "منسوخ کریں",
    "remove": "ہٹائیں",
    "doYouReallyWantToRemove": "کیا آپ واقعی '#'? کو ہٹانا چاہتے ہیں؟",
    "openTime": "کھلنے کا وقت",
    "closeTime": "بند ہونے کا وقت",
    "profile": "پروفائل",
    "appDoesNotHaveLocationPermission":
        "ایپ کے پاس مقام کی اجازت نہیں ہے۔ درست نتائج حاصل کرنے کے لیے آپ کو دستی طور پر مقام منتخب کرنا ہوگا۔",
    "important": "اہم",
    "noInternet": "کوئی انٹرنیٹ نہیں",
    "thereIsNoInternetConnectivity": "انٹرنیٹ کنیکٹیویٹی دستیاب نہیں ہے۔",
    "doYouWantToDeleteBusinessService":
        "کیا آپ اس کاروبار/سروس کو حذف کرنا چاہتے ہیں؟",
    "active": "فعال",
    "editBusinessService": "کاروبار/سروس میں ترمیم کریں",
    "okay": "ٹھیک ہے",
    "loginRequired": "لاگ ان ضروری ہے",
    "pleaseLoginToUseThisFeature":
        "براہ کرم اس خصوصیت کو استعمال کرنے کے لیے لاگ ان کریں۔",
    "doYouWantToLogout": "کیا آپ لاگ آؤٹ کرنا چاہتے ہیں؟",
    "history": "تاریخ",
    "clear": "صاف کریں",
    "doYouWantToDeleteThisBusinessServiceFromHistory":
        "کیا آپ اس کاروبار/سروس کو تاریخ سے حذف کرنا چاہتے ہیں؟",
    "doYouWantToDeleteAllBusinessesServicesFromHistory":
        "کیا آپ تمام کاروبار/سروسز کو تاریخ سے حذف کرنا چاہتے ہیں؟",
    "noChats": "ابھی کوئی چیٹس نہیں",
    "allChatsWillBeShownHere": "تمام چیٹس یہاں دکھائی جائیں گی۔",
    "doYouWantToDeleteThisMessage": "کیا آپ اس پیغام کو حذف کرنا چاہتے ہیں؟",
    "selectVideoSource": "ویڈیو کا ماخذ منتخب کریں",
    "video": "ویڈیو",
    "audio": "آڈیو",
    "pdf": "PDF",
    "image": "تصویر",
    "typing": "ٹائپنگ...",
    "callHasBeenDisabledByTheBusinessService":
        "کاروبار/سروس نے کال کو غیر فعال کر دیا ہے۔",
    "messageHasBeenDisabledByTheBusinessService":
        "کاروبار/سروس نے پیغام کو غیر فعال کر دیا ہے۔",
    "loadingLocalBusinessAndServices":
        "مقامی \nکاروبار \nاور \nسروسز لوڈ ہو رہی ہیں",
    "sortByDistance": "فاصلہ کے لحاظ سے ترتیب دیں",
    "sortByRating": "درجہ بندی کے لحاظ سے ترتیب دیں",
    "feedback": "رائے",
    "writeYourFeedbackHere": "اپنی رائے یہاں لکھیں...",
    "verifyYourBusinessService": "اپنے کاروبار اور سروس کی تصدیق کریں",
    "verificationForm": "تصدیقی فارم",
    "allSubmissions": "تمام جمع کردہ",
    "documentFile": "دستاویز فائل",
    "documentType": "دستاویز کی قسم",
    "documentNumber": "دستاویز نمبر",
    "businessService": "کاروبار/سروس",
    "docFile": "دستاویز فائل",
    "docType": "دستاویز کی قسم",
    "docNumber": "دستاویز نمبر",
    "view": "دیکھیں",
    "verified": "تصدیق شدہ",
    "status": "حیثیت",
    "reason": "وجہ",
    "date": "تاریخ",
    "notification": "اطلاع",
    "notifications": "اطلاعات",
    "doYouWantToDeleteThisNotification":
        "کیا آپ اس اطلاع کو حذف کرنا چاہتے ہیں؟",
    "noNotifications": "ابھی کوئی اطلاعات نہیں",
    "deleteAccount": "اکاؤنٹ حذف کریں",
    "whyDoYouWantToDeleteYourAccount":
        "آپ اپنا اکاؤنٹ حذف کرنا کیوں چاہتے ہیں؟",
    "writeYourReasonHere": "اپنا سبب یہاں لکھیں...",
    "reasonIsRequired": "سبب ضروری ہے۔",
    "reasonMustBeAtLeast10Characters":
        "وجہ کم از کم\n10 حروف پر مشتمل ہونی چاہیے۔",
    "selectLanguage": "زبان منتخب کریں",
    "english": "English",
    "hindi": "हिंदी",
    "bengali": "বাংলা",
    "kannada": "ಕನ್ನಡ",
    "urdu": "اردو",
    "punjabi": "ਪੰਜਾਬੀ",
    "gujarati": "ગુજરાતી",
    "marathi": "मराठी",
    "fullNameIsRequired": "پورا نام ضروری ہے۔",
    "mobileNumberIsRequired": "موبائل نمبر ضروری ہے۔",
    "enterAValid10DigitMobileNumber": "درست 10 ہندسوں کا موبائل نمبر درج کریں۔",
    "emailIsRequired": "ای میل ضروری ہے۔",
    "enterAValidEmailAddress": "درست ای میل پتہ درج کریں۔",
    "passwordIsRequired": "پاس ورڈ ضروری ہے۔",
    "passwordMustHaveAtLeast8Characters":
        "پاس ورڈ میں کم از کم 8 حروف ہونے چاہئیں۔",
    "fieldIsRequired": "یہ فیلڈ ضروری ہے۔",
    "thePasswordMustContainAtLeast":
        "پاس ورڈ میں کم از کم ایک بڑا حرف، ایک چھوٹا حرف اور ایک نمبر ہونا چاہیے۔",
    "passwordsDoNotMatch": "پاس ورڈز میل نہیں کھاتے۔",
    "imageIsRequired": "تصویر ضروری ہے۔",
    "nameIsRequired": "نام ضروری ہے۔",
    "addressIsRequired": "پتہ ضروری ہے۔",
    "typeIsRequired": "قسم ضروری ہے۔",
    "categoryIsRequired": "زمرہ ضروری ہے۔",
    "countryIsRequired": "ملک ضروری ہے۔",
    "stateIsRequired": "ریاست ضروری ہے۔",
    "cityIsRequired": "شہر ضروری ہے۔",
    "pleaseAddAtLeastOneProductService":
        "براہ کرم کم از کم ایک مصنوع یا سروس شامل کریں۔",
    "openTimeIsRequired": "کھلنے کا وقت ضروری ہے۔",
    "closeTimeIsRequired": "بند ہونے کا وقت ضروری ہے۔",
    "feedbackIsRequired": "رائے ضروری ہے۔",
    "documentTypeIsRequired": "دستاویز کی قسم ضروری ہے۔",
    "businessServiceIsRequired": "کاروبار/سروس ضروری ہے۔",
    "documentNumberIsRequired": "دستاویز نمبر ضروری ہے۔",
    "documentImageIsRequired": "دستاویز کی تصویر ضروری ہے۔",
  };

  final Map<String, String> _punjabi = {
    "appName": "MVVM GetX",
    "confirm": "ਪੁਸ਼ਟੀ ਕਰੋ",
    "doYouWantToExitTheApp": "ਕੀ ਤੁਸੀਂ ਐਪ ਤੋਂ ਬਾਹਰ ਜਾਣਾ ਚਾਹੁੰਦੇ ਹੋ?",
    "yes": "ਹਾਂ",
    "no": "ਨਹੀਂ",
    "login": "ਲੌਗਇਨ",
    "register": "ਰਜਿਸਟਰ ਕਰੋ",
    "doNotHaveAnAccount": "ਕੀ ਤੁਹਾਡਾ ਖਾਤਾ ਨਹੀਂ ਹੈ?",
    "fullName": "ਪੂਰਾ ਨਾਂ",
    "mobileNumber": "ਮੋਬਾਈਲ ਨੰਬਰ",
    "verifyYourMobileNo": "ਆਪਣਾ ਮੋਬਾਈਲ ਨੰਬਰ ਵੇਰਿਫਾਈ ਕਰੋ",
    "verifyOTP": "OTP ਵੇਰਿਫਾਈ ਕਰੋ",
    "enterOTP": "ਇੱਥੇ OTP ਦਾਖਲ ਕਰੋ:",
    "submit": "ਜਮ੍ਹਾਂ ਕਰੋ",
    "didNotGetOTP": "OTP ਨਹੀਂ ਮਿਲਿਆ?",
    "resendNow": "ਹੁਣੇ ਭੇਜੋ",
    "confirmPassword": "ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ",
    "alreadyHaveAnAccount": "ਪਹਿਲਾਂ ਹੀ ਖਾਤਾ ਹੈ?",
    "logout": "ਲੌਗ ਆਉਟ",
    "update": "ਅੱਪਡੇਟ",
    "noDataAvailable": "ਕੋਈ ਡਾਟਾ ਉਪਲਬਧ ਨਹੀਂ",
    "thereIsNoDataToBeShown": "ਇੱਥੇ ਵੇਖਾਉਣ ਲਈ ਕੋਈ ਡਾਟਾ ਉਪਲਬਧ ਨਹੀਂ ਹੈ।",
    "myBusinessAndService": "ਮੇਰਾ ਕਾਰੋਬਾਰ ਅਤੇ ਸੇਵਾ",
    "search_": "ਖੋਜੋ...",
    "categories": "ਸ਼੍ਰੇਣੀਆਂ",
    "viewMore": "ਹੋਰ ਵੇਖੋ",
    "location": "ਟਿਕਾਣਾ",
    "call": "ਕਾਲ ਕਰੋ",
    "message": "ਸੁਨੇਹਾ",
    "businesses": "ਕਾਰੋਬਾਰ",
    "services": "ਸੇਵਾਵਾਂ",
    "change": "ਬਦਲੋ",
    "searchCategory": "ਸ਼੍ਰੇਣੀ ਖੋਜੋ",
    "searchService": "ਸੇਵਾ ਖੋਜੋ",
    "searchBusiness": "ਕਾਰੋਬਾਰ ਖੋਜੋ",
    "search": "ਖੋਜੋ",
    "noSearchResultTitle": "ਮਾਫ ਕਰਨਾ, ਕੋਈ ਨਤੀਜੇ ਨਹੀਂ ਮਿਲੇ",
    "noSearchResultSubtitle": "ਤੁਸੀਂ ਜੋ ਖੋਜਿਆ ਉਹ ਨਹੀਂ ਮਿਲਿਆ ਜਾਂ ਮੌਜੂਦ ਨਹੀਂ ਹੈ",
    "fromYourCurrentLocation": "ਤੁਹਾਡੇ ਮੌਜੂਦਾ ਟਿਕਾਣੇ ਤੋਂ",
    "rateIt": "ਰੇਟ ਕਰੋ",
    "howWasYourExperience": "ਤੁਹਾਡਾ ਅਨੁਭਵ ਕਿਵੇਂ ਰਿਹਾ?",
    "add": "ਸ਼ਾਮਲ ਕਰੋ",
    "edit": "ਸੋਧੋ",
    "delete": "ਹਟਾਓ",
    "addBusinessService": "ਕਾਰੋਬਾਰ/ਸੇਵਾ ਸ਼ਾਮਲ ਕਰੋ",
    "selectImageSource": "ਚਿੱਤਰ ਸਰੋਤ ਚੁਣੋ",
    "gallery": "ਗੈਲਰੀ",
    "camera": "ਕੈਮਰਾ",
    "fileSizeMustBeSmallerThan": "ਫਾਈਲ ਆਕਾਰ ਇਸ ਤੋਂ ਛੋਟਾ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ",
    "name": "ਨਾਂ",
    "address": "ਪਤਾ",
    "save": "ਸੰਭਾਲੋ",
    "type": "ਕਿਸਮ",
    "category": "ਸ਼੍ਰੇਣੀ",
    "country": "ਦੇਸ਼",
    "state": "ਰਾਜ",
    "city": "ਸ਼ਹਿਰ",
    "currentLocation": "ਮੌਜੂਦਾ ਟਿਕਾਣਾ",
    "selectLocation": "ਟਿਕਾਣਾ ਚੁਣੋ",
    "selectedLocation": "ਚੁਣਿਆ ਹੋਇਆ ਟਿਕਾਣਾ",
    "productsAndOrServices": "ਉਤਪਾਦ ਅਤੇ/ਜਾਂ ਸੇਵਾਵਾਂ",
    "selectFromMap": "ਨਕਸ਼ੇ ਤੋਂ ਚੁਣੋ",
    "pickLocation": "ਟਿਕਾਣਾ ਚੁਣੋ",
    "or": "ਜਾਂ",
    "removeItem": "ਆਈਟਮ ਹਟਾਓ",
    "cancel": "ਰੱਦ ਕਰੋ",
    "remove": "ਹਟਾਓ",
    "doYouReallyWantToRemove": "ਕੀ ਤੁਸੀਂ '#'-ਨੂੰ ਸੱਚਮੁੱਚ ਹਟਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ?",
    "openTime": "ਖੁੱਲਣ ਦਾ ਸਮਾਂ",
    "closeTime": "ਬੰਦ ਹੋਣ ਦਾ ਸਮਾਂ",
    "profile": "ਪਰੋਫ਼ਾਈਲ",
    "appDoesNotHaveLocationPermission":
        "ਐਪ ਕੋਲ ਟਿਕਾਣੇ ਦੀ ਇਜਾਜ਼ਤ ਨਹੀਂ ਹੈ। ਠੀਕ ਨਤੀਜੇ ਪ੍ਰਾਪਤ ਕਰਨ ਲਈ ਤੁਹਾਨੂੰ ਟਿਕਾਣਾ ਹੱਥੋਂ ਚੁਣਨਾ ਪਵੇਗਾ।",
    "important": "ਮਹੱਤਵਪੂਰਨ",
    "noInternet": "ਇੰਟਰਨੈਟ ਨਹੀਂ",
    "thereIsNoInternetConnectivity": "ਇੰਟਰਨੈਟ ਕਨੈਕਸ਼ਨ ਉਪਲਬਧ ਨਹੀਂ ਹੈ।",
    "doYouWantToDeleteBusinessService":
        "ਕੀ ਤੁਸੀਂ ਇਹ ਕਾਰੋਬਾਰ/ਸੇਵਾ ਹਟਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ?",
    "active": "ਸਰਗਰਮ",
    "editBusinessService": "ਕਾਰੋਬਾਰ/ਸੇਵਾ ਸੋਧੋ",
    "okay": "ਠੀਕ ਹੈ",
    "loginRequired": "ਲੌਗਇਨ ਲਾਜ਼ਮੀ ਹੈ",
    "pleaseLoginToUseThisFeature": "ਇਹ ਫੀਚਰ ਵਰਤਣ ਲਈ ਕਿਰਪਾ ਕਰਕੇ ਲੌਗਇਨ ਕਰੋ।",
    "doYouWantToLogout": "ਕੀ ਤੁਸੀਂ ਲੌਗਆਉਟ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ?",
    "history": "ਅਤੀਤ",
    "clear": "ਸਾਫ ਕਰੋ",
    "doYouWantToDeleteThisBusinessServiceFromHistory":
        "ਕੀ ਤੁਸੀਂ ਇਹ ਕਾਰੋਬਾਰ/ਸੇਵਾ ਅਤੀਤ ਤੋਂ ਹਟਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ?",
    "doYouWantToDeleteAllBusinessesServicesFromHistory":
        "ਕੀ ਤੁਸੀਂ ਸਾਰੇ ਕਾਰੋਬਾਰ/ਸੇਵਾਵਾਂ ਨੂੰ ਅਤੀਤ ਤੋਂ ਹਟਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ?",
    "noChats": "ਹੁਣੇ ਕੋਈ ਚੈਟ ਨਹੀਂ",
    "allChatsWillBeShownHere": "ਸਾਰੀ ਚੈਟ ਇੱਥੇ ਵੇਖਾਈ ਜਾਵੇਗੀ।",
    "doYouWantToDeleteThisMessage": "ਕੀ ਤੁਸੀਂ ਇਹ ਸੁਨੇਹਾ ਹਟਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ?",
    "selectVideoSource": "ਵੀਡੀਓ ਸਰੋਤ ਚੁਣੋ",
    "video": "ਵੀਡੀਓ",
    "audio": "ਆਡੀਓ",
    "pdf": "PDF",
    "image": "ਚਿੱਤਰ",
    "typing": "ਟਾਈਪ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...",
    "callHasBeenDisabledByTheBusinessService":
        "ਕਾਰੋਬਾਰ/ਸੇਵਾ ਵੱਲੋਂ ਕਾਲ ਅਸਮਰਥ ਕਰ ਦਿੱਤੀ ਗਈ ਹੈ।",
    "messageHasBeenDisabledByTheBusinessService":
        "ਕਾਰੋਬਾਰ/ਸੇਵਾ ਵੱਲੋਂ ਸੁਨੇਹਾ ਅਸਮਰਥ ਕਰ ਦਿੱਤਾ ਗਿਆ ਹੈ।",
    "loadingLocalBusinessAndServices":
        "ਸਥਾਨਕ \nਕਾਰੋਬਾਰ \nਅਤੇ \nਸੇਵਾਵਾਂ ਲੋਡ ਕੀਤੀਆਂ ਜਾ ਰਹੀਆਂ ਹਨ",
    "sortByDistance": "ਦੂਰੀ ਅਨੁਸਾਰ ਲੜੀਬੱਧ ਕਰੋ",
    "sortByRating": "ਰੇਟਿੰਗ ਅਨੁਸਾਰ ਲੜੀਬੱਧ ਕਰੋ",
    "feedback": "ਫੀਡਬੈਕ",
    "writeYourFeedbackHere": "ਆਪਣੀ ਫੀਡਬੈਕ ਇੱਥੇ ਲਿਖੋ...",
    "verifyYourBusinessService": "ਆਪਣਾ ਕਾਰੋਬਾਰ ਅਤੇ ਸੇਵਾ ਵੇਰਿਫਾਈ ਕਰੋ",
    "verificationForm": "ਵੇਰਿਫਿਕੇਸ਼ਨ ਫਾਰਮ",
    "allSubmissions": "ਸਭ ਭੇਜਣਾਂ",
    "documentFile": "ਡੌਕੂਮੈਂਟ ਫਾਈਲ",
    "documentType": "ਡੌਕੂਮੈਂਟ ਕਿਸਮ",
    "documentNumber": "ਡੌਕੂਮੈਂਟ ਨੰਬਰ",
    "businessService": "ਕਾਰੋਬਾਰ/ਸੇਵਾ",
    "docFile": "ਡੌਕ. ਫਾਈਲ",
    "docType": "ਡੌਕ. ਕਿਸਮ",
    "docNumber": "ਡੌਕ. ਨੰ.",
    "view": "ਵੇਖੋ",
    "verified": "ਵੇਰਿਫਾਈਡ",
    "status": "ਸਥਿਤੀ",
    "reason": "ਕਾਰਨ",
    "date": "ਤਾਰੀਖ",
    "notification": "ਸੂਚਨਾ",
    "notifications": "ਸੂਚਨਾਵਾਂ",
    "doYouWantToDeleteThisNotification": "ਕੀ ਤੁਸੀਂ ਇਹ ਸੂਚਨਾ ਹਟਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ?",
    "noNotifications": "ਹੁਣੇ ਕੋਈ ਸੂਚਨਾ ਨਹੀਂ",
    "deleteAccount": "ਖਾਤਾ ਹਟਾਓ",
    "whyDoYouWantToDeleteYourAccount":
        "ਤੁਸੀਂ ਆਪਣਾ ਖਾਤਾ ਕਿਉਂ ਹਟਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ?",
    "writeYourReasonHere": "ਆਪਣਾ ਕਾਰਨ ਇੱਥੇ ਲਿਖੋ...",
    "reasonIsRequired": "ਕਾਰਨ ਲਾਜ਼ਮੀ ਹੈ।",
    "reasonMustBeAtLeast10Characters":
        "ਕਾਰਨ ਘੱਟੋ-ਘੱਟ\n10 ਅੱਖਰ ਲੰਬਾ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ।",
    "selectLanguage": "ਭਾਸ਼ਾ ਚੁਣੋ",
    "english": "English",
    "hindi": "हिंदी",
    "bengali": "বাংলা",
    "kannada": "ಕನ್ನಡ",
    "urdu": "اردو",
    "punjabi": "ਪੰਜਾਬੀ",
    "gujarati": "ગુજરાતી",
    "marathi": "मराठी",
    "fullNameIsRequired": "ਪੂਰਾ ਨਾਂ ਲਾਜ਼ਮੀ ਹੈ।",
    "mobileNumberIsRequired": "ਮੋਬਾਈਲ ਨੰਬਰ ਲਾਜ਼ਮੀ ਹੈ।",
    "enterAValid10DigitMobileNumber": "ਠੀਕ 10 ਅੰਕਾਂ ਵਾਲਾ ਮੋਬਾਈਲ ਨੰਬਰ ਦਾਖਲ ਕਰੋ।",
    "emailIsRequired": "ਈਮੇਲ ਲਾਜ਼ਮੀ ਹੈ।",
    "enterAValidEmailAddress": "ਠੀਕ ਈਮੇਲ ਐਡਰੈੱਸ ਦਾਖਲ ਕਰੋ।",
    "passwordIsRequired": "ਪਾਸਵਰਡ ਲਾਜ਼ਮੀ ਹੈ।",
    "passwordMustHaveAtLeast8Characters":
        "ਪਾਸਵਰਡ ਵਿੱਚ ਘੱਟੋ-ਘੱਟ 8 ਅੱਖਰ ਹੋਣੇ ਚਾਹੀਦੇ ਹਨ।",
    "fieldIsRequired": "ਇਹ ਖੇਤਰ ਲਾਜ਼ਮੀ ਹੈ।",
    "thePasswordMustContainAtLeast":
        "ਪਾਸਵਰਡ ਵਿੱਚ ਘੱਟੋ-ਘੱਟ ਇੱਕ ਵੱਡੀ ਅੱਖਰ, ਇੱਕ ਛੋਟੀ ਅੱਖਰ ਅਤੇ ਇੱਕ ਨੰਬਰ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ।",
    "passwordsDoNotMatch": "ਪਾਸਵਰਡ ਮੇਲ ਨਹੀਂ ਖਾਂਦੇ।",
    "imageIsRequired": "ਚਿੱਤਰ ਲਾਜ਼ਮੀ ਹੈ।",
    "nameIsRequired": "ਨਾਂ ਲਾਜ਼ਮੀ ਹੈ।",
    "addressIsRequired": "ਪਤਾ ਲਾਜ਼ਮੀ ਹੈ।",
    "typeIsRequired": "ਕਿਸਮ ਲਾਜ਼ਮੀ ਹੈ।",
    "categoryIsRequired": "ਸ਼੍ਰੇਣੀ ਲਾਜ਼ਮੀ ਹੈ।",
    "countryIsRequired": "ਦੇਸ਼ ਲਾਜ਼ਮੀ ਹੈ।",
    "stateIsRequired": "ਰਾਜ ਲਾਜ਼ਮੀ ਹੈ।",
    "cityIsRequired": "ਸ਼ਹਿਰ ਲਾਜ਼ਮੀ ਹੈ।",
    "pleaseAddAtLeastOneProductService":
        "ਕਿਰਪਾ ਕਰਕੇ ਘੱਟੋ-ਘੱਟ ਇੱਕ ਉਤਪਾਦ ਜਾਂ ਸੇਵਾ ਸ਼ਾਮਲ ਕਰੋ।",
    "openTimeIsRequired": "ਖੁੱਲਣ ਦਾ ਸਮਾਂ ਲਾਜ਼ਮੀ ਹੈ।",
    "closeTimeIsRequired": "ਬੰਦ ਹੋਣ ਦਾ ਸਮਾਂ ਲਾਜ਼ਮੀ ਹੈ।",
    "feedbackIsRequired": "ਫੀਡਬੈਕ ਲਾਜ਼ਮੀ ਹੈ।",
    "documentTypeIsRequired": "ਡੌਕੂਮੈਂਟ ਕਿਸਮ ਲਾਜ਼ਮੀ ਹੈ।",
    "businessServiceIsRequired": "ਕਾਰੋਬਾਰ/ਸੇਵਾ ਲਾਜ਼ਮੀ ਹੈ।",
    "documentNumberIsRequired": "ਡੌਕੂਮੈਂਟ ਨੰਬਰ ਲਾਜ਼ਮੀ ਹੈ।",
    "documentImageIsRequired": "ਡੌਕੂਮੈਂਟ ਚਿੱਤਰ ਲਾਜ਼ਮੀ ਹੈ।",
  };

  final Map<String, String> _gujarati = {
    "appName": "MVVM GetX",
    "confirm": "પુષ્ટિ કરો",
    "doYouWantToExitTheApp": "શું તમે એપ્લિકેશનમાંથી બહાર નીકળવા માંગો છો?",
    "yes": "હા",
    "no": "ના",
    "login": "લૉગિન",
    "register": "નોંધણી કરો",
    "doNotHaveAnAccount": "ખાતું નથી?",
    "fullName": "પૂર્ણ નામ",
    "mobileNumber": "મોબાઇલ નંબર",
    "verifyYourMobileNo": "તમારો મોબાઇલ નંબર ચકાસો",
    "verifyOTP": "OTP ચકાસો",
    "enterOTP": "અહીં OTP દાખલ કરો:",
    "submit": "સબમિટ કરો",
    "didNotGetOTP": "OTP મળ્યો નથી?",
    "resendNow": "હવે ફરીથી મોકલો",
    "confirmPassword": "પાસવર્ડ પુષ્ટિ કરો",
    "alreadyHaveAnAccount": "પહેલેથી જ ખાતું છે?",
    "logout": "લૉગઆઉટ",
    "update": "અપડેટ કરો",
    "noDataAvailable": "કોઈ ડેટા ઉપલબ્ધ નથી",
    "thereIsNoDataToBeShown": "અહીં બતાવવા માટે કોઈ ડેટા ઉપલબ્ધ નથી.",
    "myBusinessAndService": "મારું વ્યવસાય અને સેવા",
    "search_": "શોધો...",
    "categories": "શ્રેણીઓ",
    "viewMore": "વધુ જુઓ",
    "location": "સ્થાન",
    "call": "કૉલ કરો",
    "message": "સંદેશ",
    "businesses": "વ્યવસાયો",
    "services": "સેવાઓ",
    "change": "બદલો",
    "searchCategory": "શ્રેણી શોધો",
    "searchService": "સેવા શોધો",
    "searchBusiness": "વ્યવસાય શોધો",
    "search": "શોધો",
    "noSearchResultTitle": "માફ કરો, કોઈ પરિણામ મળ્યું નથી",
    "noSearchResultSubtitle":
        "તમે જે શોધ્યું તે મળ્યું નથી અથવા અસ્તિત્વમાં નથી",
    "fromYourCurrentLocation": "તમારા વર્તમાન સ્થાનથી",
    "rateIt": "મૂલ્યાંકન કરો",
    "howWasYourExperience": "તમારો અનુભવ કેવો રહ્યો?",
    "add": "ઉમેરો",
    "edit": "સંપાદિત કરો",
    "delete": "કાઢી નાખો",
    "addBusinessService": "વ્યવસાય/સેવા ઉમેરો",
    "selectImageSource": "છબી સ્ત્રોત પસંદ કરો",
    "gallery": "ગેલેરી",
    "camera": "કેમેરા",
    "fileSizeMustBeSmallerThan": "ફાઇલનું કદ ઓછું હોવું જોઈએ",
    "name": "નામ",
    "address": "સરનામું",
    "save": "સાચવો",
    "type": "પ્રકાર",
    "category": "શ્રેણી",
    "country": "દેશ",
    "state": "રાજ્ય",
    "city": "શહેર",
    "currentLocation": "વર્તમાન સ્થાન",
    "selectLocation": "સ્થાન પસંદ કરો",
    "selectedLocation": "પસંદ કરેલું સ્થાન",
    "productsAndOrServices": "ઉત્પાદનો અને/અથવા સેવાઓ",
    "selectFromMap": "નકશામાંથી પસંદ કરો",
    "pickLocation": "સ્થાન પસંદ કરો",
    "or": "અથવા",
    "removeItem": "આઇટમ કાઢી નાખો",
    "cancel": "રદ કરો",
    "remove": "કાઢી નાખો",
    "doYouReallyWantToRemove": "શું તમે ખરેખર '#' કાઢી નાખવા માંગો છો?",
    "openTime": "ખુલવાનો સમય",
    "closeTime": "બંધ થવાનો સમય",
    "profile": "પ્રોફાઇલ",
    "appDoesNotHaveLocationPermission":
        "એપ્લિકેશન પાસે સ્થાનની પરવાનગી નથી. યોગ્ય પરિણામ મેળવવા માટે તમારે સ્થાન મેન્યુઅલી પસંદ કરવું પડશે.",
    "important": "મહત્વપૂર્ણ",
    "noInternet": "ઇન્ટરનેટ નથી",
    "thereIsNoInternetConnectivity": "ઇન્ટરનેટ કનેક્ટિવિટી ઉપલબ્ધ નથી.",
    "doYouWantToDeleteBusinessService":
        "શું તમે આ વ્યવસાય/સેવા કાઢી નાખવા માંગો છો?",
    "active": "સક્રિય",
    "editBusinessService": "વ્યવસાય/સેવા સંપાદિત કરો",
    "okay": "બરાબર",
    "loginRequired": "લૉગિન જરૂરી છે",
    "pleaseLoginToUseThisFeature":
        "આ સુવિધાનો ઉપયોગ કરવા માટે કૃપા કરીને લૉગિન કરો.",
    "doYouWantToLogout": "શું તમે લૉગઆઉટ કરવા માંગો છો?",
    "history": "ઇતિહાસ",
    "clear": "સાફ કરો",
    "doYouWantToDeleteThisBusinessServiceFromHistory":
        "શું તમે ઇતિહાસમાંથી આ વ્યવસાય/સેવા કાઢી નાખવા માંગો છો?",
    "doYouWantToDeleteAllBusinessesServicesFromHistory":
        "શું તમે ઇતિહાસમાંથી બધા વ્યવસાયો/સેવાઓ કાઢી નાખવા માંગો છો?",
    "noChats": "હાલમાં કોઈ ચેટ નથી",
    "allChatsWillBeShownHere": "બધી ચેટ્સ અહીં બતાવવામાં આવશે.",
    "doYouWantToDeleteThisMessage": "શું તમે આ સંદેશ કાઢી નાખવા માંગો છો?",
    "selectVideoSource": "વિડિયો સ્ત્રોત પસંદ કરો",
    "video": "વિડિયો",
    "audio": "ઓડિયો",
    "pdf": "PDF",
    "image": "છબી",
    "typing": "ટાઇપ કરી રહ્યા છીએ...",
    "callHasBeenDisabledByTheBusinessService":
        "કૉલ વ્યવસાય/સેવા દ્વારા અક્ષમ કરવામાં આવ્યો છે.",
    "messageHasBeenDisabledByTheBusinessService":
        "સંદેશ વ્યવસાય/સેવા દ્વારા અક્ષમ કરવામાં આવ્યો છે.",
    "loadingLocalBusinessAndServices":
        "સ્થાનિક \nવ્યવસાય \nઅને \nસેવાઓ લોડ કરી રહ્યા છીએ",
    "sortByDistance": "અંતરના આધારે ગોઠવો",
    "sortByRating": "રેટિંગના આધારે ગોઠવો",
    "feedback": "પ્રતિસાદ",
    "writeYourFeedbackHere": "અહીં તમારો પ્રતિસાદ લખો...",
    "verifyYourBusinessService": "તમારું વ્યવસાય અને સેવા ચકાસો",
    "verificationForm": "ચકાસણી ફોર્મ",
    "allSubmissions": "બધી સબમિશન્સ",
    "documentFile": "દસ્તાવેજ ફાઇલ",
    "documentType": "દસ્તાવેજ પ્રકાર",
    "documentNumber": "દસ્તાવેજ નંબર",
    "businessService": "વ્યવસાય/સેવા",
    "docFile": "દસ્તાવેજ ફાઇલ",
    "docType": "દસ્તાવેજ પ્રકાર",
    "docNumber": "દસ્તાવેજ નંબર",
    "view": "જુઓ",
    "verified": "ચકાસાયેલ",
    "status": "સ્થિતિ",
    "reason": "કારણ",
    "date": "તારીખ",
    "notification": "સૂચના",
    "notifications": "સૂચનાઓ",
    "doYouWantToDeleteThisNotification": "શું તમે આ સૂચના કાઢી નાખવા માંગો છો?",
    "noNotifications": "હાલમાં કોઈ સૂચનાઓ નથી",
    "deleteAccount": "ખાતું કાઢી નાખો",
    "whyDoYouWantToDeleteYourAccount":
        "તમે તમારું ખાતું કાઢી શા માટે નાખવા માંગો છો?",
    "writeYourReasonHere": "તમારું કારણ અહીં લખો...",
    "reasonIsRequired": "કારણ જરૂરી છે.",
    "reasonMustBeAtLeast10Characters":
        "કારણ ઓછામાં ઓછું\n10 અક્ષરો લાંબું હોવું જોઈએ.",
    "selectLanguage": "ભાષા પસંદ કરો",
    "english": "English",
    "hindi": "हिंदी",
    "bengali": "বাংলা",
    "kannada": "ಕನ್ನಡ",
    "urdu": "اردو",
    "punjabi": "ਪੰਜਾਬੀ",
    "gujarati": "ગુજરાતી",
    "marathi": "मराठी",
    "fullNameIsRequired": "પૂર્ણ નામ જરૂરી છે.",
    "mobileNumberIsRequired": "મોબાઇલ નંબર જરૂરી છે.",
    "enterAValid10DigitMobileNumber": "માન્ય 10 અંકનો મોબાઇલ નંબર દાખલ કરો.",
    "emailIsRequired": "ઇમેઇલ જરૂરી છે.",
    "enterAValidEmailAddress": "માન્ય ઇમેઇલ સરનામું દાખલ કરો.",
    "passwordIsRequired": "પાસવર્ડ જરૂરી છે.",
    "passwordMustHaveAtLeast8Characters":
        "પાસવર્ડમાં ઓછામાં ઓછા 8 અક્ષરો હોવા જોઈએ.",
    "fieldIsRequired": "ક્ષેત્ર જરૂરી છે.",
    "thePasswordMustContainAtLeast":
        "પાસવર્ડમાં ઓછામાં ઓછું એક મોટા અક્ષર, એક નાના અક્ષર અને એક નંબર હોવો જોઈએ.",
    "passwordsDoNotMatch": "પાસવર્ડ મેળ ખાતા નથી.",
    "imageIsRequired": "છબી જરૂરી છે.",
    "nameIsRequired": "નામ જરૂરી છે.",
    "addressIsRequired": "સરનામું જરૂરી છે.",
    "typeIsRequired": "પ્રકાર જરૂરી છે.",
    "categoryIsRequired": "શ્રેણી જરૂરી છે.",
    "countryIsRequired": "દેશ જરૂરી છે.",
    "stateIsRequired": "રાજ્ય જરૂરી છે.",
    "cityIsRequired": "શહેર જરૂરી છે.",
    "pleaseAddAtLeastOneProductService":
        "કૃપા કરીને ઓછામાં ઓછું એક ઉત્પાદન અથવા સેવા ઉમેરો.",
    "openTimeIsRequired": "ખુલવાનો સમય જરૂરી છે.",
    "closeTimeIsRequired": "બંધ થવાનો સમય જરૂરી છે.",
    "feedbackIsRequired": "પ્રતિસાદ જરૂરી છે.",
    "documentTypeIsRequired": "દસ્તાવેજ પ્રકાર જરૂરી છે.",
    "businessServiceIsRequired": "વ્યવસાય/સેવા જરૂરી છે.",
    "documentNumberIsRequired": "દસ્તાવેજ નંબર જરૂરી છે.",
    "documentImageIsRequired": "દસ્તાવેજ છબી જરૂરી છે.",
  };

  final Map<String, String> _marathi = {
    "appName": "MVVM GetX",
    "confirm": "पुष्टी करा",
    "doYouWantToExitTheApp": "आपण अ‍ॅपमधून बाहेर पडू इच्छिता?",
    "yes": "होय",
    "no": "नाही",
    "login": "लॉगिन",
    "register": "नोंदणी करा",
    "doNotHaveAnAccount": "खाते नाही?",
    "fullName": "पूर्ण नाव",
    "mobileNumber": "मोबाईल नंबर",
    "verifyYourMobileNo": "आपला मोबाईल नंबर सत्यापित करा.",
    "verifyOTP": "OTP सत्यापित करा",
    "enterOTP": "OTP येथे प्रविष्ट करा:",
    "submit": "सबमिट करा",
    "didNotGetOTP": "OTP मिळाला नाही",
    "resendNow": "पुन्हा पाठवा",
    "confirmPassword": "पासवर्ड पुष्टी करा",
    "alreadyHaveAnAccount": "आधीच खाते आहे?",
    "logout": "बाहेर पडा",
    "update": "अपडेट करा",
    "noDataAvailable": "डेटा उपलब्ध नाही",
    "thereIsNoDataToBeShown": "येथे दर्शविण्यासाठी कोणताही डेटा उपलब्ध नाही.",
    "myBusinessAndService": "माझा व्यवसाय आणि सेवा",
    "search_": "शोधा...",
    "categories": "श्रेण्या",
    "viewMore": "अधिक पहा",
    "location": "स्थान",
    "call": "कॉल",
    "message": "संदेश",
    "businesses": "व्यवसाय",
    "services": "सेवा",
    "change": "बदला",
    "searchCategory": "श्रेणी शोधा",
    "searchService": "सेवा शोधा",
    "searchBusiness": "व्यवसाय शोधा",
    "search": "शोधा",
    "noSearchResultTitle": "क्षमस्व, कोणतेही परिणाम सापडले नाहीत",
    "noSearchResultSubtitle":
        "आपण शोधलेले दुर्दैवाने सापडले नाही किंवा अस्तित्वात नाही",
    "fromYourCurrentLocation": "आपल्या वर्तमान स्थानापासून",
    "rateIt": "रेट करा",
    "howWasYourExperience": "आपला अनुभव कसा होता?",
    "add": "जोडा",
    "edit": "संपादित करा",
    "delete": "हटवा",
    "addBusinessService": "व्यवसाय/सेवा जोडा",
    "selectImageSource": "प्रतिमा स्रोत निवडा",
    "gallery": "गॅलरी",
    "camera": "कॅमेरा",
    "fileSizeMustBeSmallerThan": "फाइलचा आकार यापेक्षा लहान असावा",
    "name": "नाव",
    "address": "पत्ता",
    "save": "जतन करा",
    "type": "प्रकार",
    "category": "श्रेणी",
    "country": "देश",
    "state": "राज्य",
    "city": "शहर",
    "currentLocation": "वर्तमान स्थान",
    "selectLocation": "स्थान निवडा",
    "selectedLocation": "निवडलेले स्थान",
    "productsAndOrServices": "उत्पादने आणि/किंवा सेवा",
    "selectFromMap": "नकाशावरून निवडा",
    "pickLocation": "स्थान निवडा",
    "or": "किंवा",
    "removeItem": "घटक हटवा",
    "cancel": "रद्द करा",
    "remove": "हटवा",
    "doYouReallyWantToRemove": "आपण '#'? हटवू इच्छिता?",
    "openTime": "उघडण्याची वेळ",
    "closeTime": "बंद होण्याची वेळ",
    "profile": "प्रोफाइल",
    "appDoesNotHaveLocationPermission":
        "अ‍ॅपकडे स्थान परवानगी नाही. योग्य परिणाम मिळवण्यासाठी आपल्याला स्थान मॅन्युअली निवडावे लागेल.",
    "important": "महत्त्वाचे",
    "noInternet": "इंटरनेट नाही",
    "thereIsNoInternetConnectivity": "इंटरनेट कनेक्टिव्हिटी नाही.",
    "doYouWantToDeleteBusinessService": "आपण हा व्यवसाय/सेवा हटवू इच्छिता?",
    "active": "सक्रिय",
    "editBusinessService": "व्यवसाय/सेवा संपादित करा",
    "okay": "ठीक आहे",
    "loginRequired": "लॉगिन आवश्यक आहे",
    "pleaseLoginToUseThisFeature": "ही सुविधा वापरण्यासाठी कृपया लॉगिन करा.",
    "doYouWantToLogout": "आपण लॉगआउट करू इच्छिता?",
    "history": "इतिहास",
    "clear": "साफ करा",
    "doYouWantToDeleteThisBusinessServiceFromHistory":
        "आपण इतिहासातून हा व्यवसाय/सेवा हटवू इच्छिता?",
    "doYouWantToDeleteAllBusinessesServicesFromHistory":
        "आपण इतिहासातून सर्व व्यवसाय/सेवा हटवू इच्छिता?",
    "noChats": "सध्या कोणतेही चॅट्स नाहीत",
    "allChatsWillBeShownHere": "सर्व चॅट्स येथे दर्शविले जातील.",
    "doYouWantToDeleteThisMessage": "आपण हा संदेश हटवू इच्छिता?",
    "selectVideoSource": "व्हिडिओ स्रोत निवडा",
    "video": "व्हिडिओ",
    "audio": "ऑडिओ",
    "pdf": "PDF",
    "image": "प्रतिमा",
    "typing": "टाइपिंग...",
    "callHasBeenDisabledByTheBusinessService":
        "कॉल व्यवसाय/सेवेद्वारे अक्षम केला गेला आहे.",
    "messageHasBeenDisabledByTheBusinessService":
        "संदेश व्यवसाय/सेवेद्वारे अक्षम केला गेला आहे.",
    "loadingLocalBusinessAndServices":
        "स्थानिक \nव्यवसाय \nआणि \nसेवा लोड करत आहे",
    "sortByDistance": "अंतरानुसार क्रमवारी लावा",
    "sortByRating": "रेटिंगनुसार क्रमवारी लावा",
    "feedback": "अभिप्राय",
    "writeYourFeedbackHere": "आपला अभिप्राय येथे लिहा...",
    "verifyYourBusinessService": "आपला व्यवसाय आणि सेवा सत्यापित करा",
    "verificationForm": "सत्यापन फॉर्म",
    "allSubmissions": "सर्व सबमिशन्स",
    "documentFile": "दस्तऐवज फाइल",
    "documentType": "दस्तऐवज प्रकार",
    "documentNumber": "दस्तऐवज क्रमांक",
    "businessService": "व्यवसाय/सेवा",
    "docFile": "दस्त. फाइल",
    "docType": "दस्त. प्रकार",
    "docNumber": "दस्त. क्र.",
    "view": "पहा",
    "verified": "सत्यापित",
    "status": "स्थिती",
    "reason": "कारण",
    "date": "तारीख",
    "notification": "सूचना",
    "notifications": "सूचना",
    "doYouWantToDeleteThisNotification": "आपण ही सूचना हटवू इच्छिता?",
    "noNotifications": "सध्या कोणत्याही सूचना नाहीत",
    "deleteAccount": "खाते हटवा",
    "whyDoYouWantToDeleteYourAccount": "आपण आपले खाते का हटवू इच्छिता?",
    "writeYourReasonHere": "आपला कारण येथे लिहा...",
    "reasonIsRequired": "कारण आवश्यक आहे.",
    "reasonMustBeAtLeast10Characters": "कारण किमान\n10 अक्षरे लांब असावे.",
    "selectLanguage": "भाषा निवडा",
    "english": "English",
    "hindi": "हिंदी",
    "bengali": "বাংলা",
    "kannada": "ಕನ್ನಡ",
    "urdu": "اردو",
    "punjabi": "ਪੰਜਾਬੀ",
    "gujarati": "ગુજરાતી",
    "marathi": "मराठी",
    "fullNameIsRequired": "पूर्ण नाव आवश्यक आहे.",
    "mobileNumberIsRequired": "मोबाईल नंबर आवश्यक आहे.",
    "enterAValid10DigitMobileNumber": "वैध 10-अंकी मोबाईल नंबर प्रविष्ट करा.",
    "emailIsRequired": "ईमेल आवश्यक आहे.",
    "enterAValidEmailAddress": "वैध ईमेल पत्ता प्रविष्ट करा.",
    "passwordIsRequired": "पासवर्ड आवश्यक आहे.",
    "passwordMustHaveAtLeast8Characters": "पासवर्डमध्ये किमान 8 अक्षरे असावीत.",
    "fieldIsRequired": "फील्ड आवश्यक आहे.",
    "thePasswordMustContainAtLeast":
        "पासवर्डमध्ये किमान एक मोठे अक्षर, एक लहान अक्षर आणि एक संख्या असावी.",
    "passwordsDoNotMatch": "पासवर्ड जुळत नाहीत.",
    "imageIsRequired": "प्रतिमा आवश्यक आहे.",
    "nameIsRequired": "नाव आवश्यक आहे.",
    "addressIsRequired": "पत्ता आवश्यक आहे.",
    "typeIsRequired": "प्रकार आवश्यक आहे.",
    "categoryIsRequired": "श्रेणी आवश्यक आहे.",
    "countryIsRequired": "देश आवश्यक आहे.",
    "stateIsRequired": "राज्य आवश्यक आहे.",
    "cityIsRequired": "शहर आवश्यक आहे.",
    "pleaseAddAtLeastOneProductService":
        "कृपया किमान एक उत्पादन किंवा सेवा जोडा.",
    "openTimeIsRequired": "उघडण्याची वेळ आवश्यक आहे.",
    "closeTimeIsRequired": "बंद होण्याची वेळ आवश्यक आहे.",
    "feedbackIsRequired": "अभिप्राय आवश्यक आहे.",
    "documentTypeIsRequired": "दस्तऐवज प्रकार आवश्यक आहे.",
    "businessServiceIsRequired": "व्यवसाय/सेवा आवश्यक आहे.",
    "documentNumberIsRequired": "दस्तऐवज क्रमांक आवश्यक आहे.",
    "documentImageIsRequired": "दस्तऐवज प्रतिमा आवश्यक आहे.",
  };
}
